[project]
name = "autogen-planatrip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "autogen-agent>=0.0.1",
    "autogen-agentchat>=0.6.2",
    "autogen-ext[ollama]>=0.6.2",
]
